[package]
name = "logbook-render"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ammonia = "4.2.1"
comrak = { version = "0.55.0", default-features = false }
logbook-core = { version = "0.1.0", path = "../logbook-core" }
syntect = { version = "5.3.0", default-features = false, features = ["parsing", "html", "default-syntaxes", "default-themes", "dump-load", "regex-fancy"] }

[dev-dependencies]
proptest = "1.11.0"
scraper = "0.27.0"
