-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [logbook_core]: function definitions
module
public import Aeneas
public import LogbookCore.Types
public import LogbookCore.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace logbook_core

/-- Trait implementation: [core::option::{impl core::fmt::Debug for core::option::Option<T>}]
    Source: '/rustc/library/core/src/option.rs', lines 592:15-592:20
    Name pattern: [core::fmt::Debug<core::option::Option<@T>>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<core::option::Option<@T>>"]
def core.option.Option.Insts.CoreFmtDebug {T : Type} (fmtDebugInst :
  core.fmt.Debug T) : core.fmt.Debug (Option T) := {
  fmt := core.option.Option.Insts.CoreFmtDebug.fmt fmtDebugInst
}

/-- [logbook_core::access::{impl core::fmt::Debug for logbook_core::access::Access}::fmt]:
    Source: 'crates/logbook-core/src/access.rs', lines 4:9-4:14
    Visibility: public -/
def access.Access.Insts.CoreFmtDebug.fmt
  (self : access.Access) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | access.Access.Public => core.fmt.Formatter.write_str f (toStr "Public")
  | access.Access.Session => core.fmt.Formatter.write_str f (toStr "Session")
  | access.Access.Auth => core.fmt.Formatter.write_str f (toStr "Auth")
  | access.Access.Owner => core.fmt.Formatter.write_str f (toStr "Owner")

/-- Trait implementation: [logbook_core::access::{impl core::fmt::Debug for logbook_core::access::Access}]
    Source: 'crates/logbook-core/src/access.rs', lines 4:9-4:14 -/
@[reducible]
def access.Access.Insts.CoreFmtDebug : core.fmt.Debug access.Access := {
  fmt := access.Access.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::access::{impl core::clone::Clone for logbook_core::access::Access}::clone]:
    Source: 'crates/logbook-core/src/access.rs', lines 4:16-4:21
    Visibility: public -/
def access.Access.Insts.CoreCloneClone.clone
  (self : access.Access) : Result access.Access := do
  ok self

/-- Trait implementation: [logbook_core::access::{impl core::clone::Clone for logbook_core::access::Access}]
    Source: 'crates/logbook-core/src/access.rs', lines 4:16-4:21 -/
@[reducible]
def access.Access.Insts.CoreCloneClone : core.clone.Clone access.Access := {
  clone := access.Access.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [logbook_core::access::{impl core::marker::Copy for logbook_core::access::Access}]
    Source: 'crates/logbook-core/src/access.rs', lines 4:23-4:27 -/
@[reducible]
def access.Access.Insts.CoreMarkerCopy : core.marker.Copy access.Access := {
  cloneInst := access.Access.Insts.CoreCloneClone
}

/-- Trait implementation: [logbook_core::access::{impl core::marker::StructuralPartialEq for logbook_core::access::Access}]
    Source: 'crates/logbook-core/src/access.rs', lines 4:29-4:38 -/
@[reducible]
def access.Access.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq access.Access := {
}

/-- [logbook_core::access::{impl core::cmp::PartialEq<logbook_core::access::Access> for logbook_core::access::Access}::eq]:
    Source: 'crates/logbook-core/src/access.rs', lines 4:29-4:38
    Visibility: public -/
def access.Access.Insts.CoreCmpPartialEqAccess.eq
  (self : access.Access) (other : access.Access) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [logbook_core::access::{impl core::cmp::PartialEq<logbook_core::access::Access> for logbook_core::access::Access}]
    Source: 'crates/logbook-core/src/access.rs', lines 4:29-4:38 -/
@[reducible]
def access.Access.Insts.CoreCmpPartialEqAccess : core.cmp.PartialEq
  access.Access access.Access := {
  eq := access.Access.Insts.CoreCmpPartialEqAccess.eq
}

/-- Trait implementation: [logbook_core::access::{impl core::cmp::Eq for logbook_core::access::Access}]
    Source: 'crates/logbook-core/src/access.rs', lines 4:40-4:42 -/
@[reducible]
impl_def access.Access.Insts.CoreCmpEq : core.cmp.Eq access.Access := {
  partialEqInst := access.Access.Insts.CoreCmpPartialEqAccess
  assert_fields_are_eq := core.cmp.Eq.assert_fields_are_eq.default
    access.Access.Insts.CoreCmpEq
}

/-- [logbook_core::access::{impl core::fmt::Debug for logbook_core::access::SessionState}::fmt]:
    Source: 'crates/logbook-core/src/access.rs', lines 17:9-17:14
    Visibility: public -/
def access.SessionState.Insts.CoreFmtDebug.fmt
  (self : access.SessionState) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | access.SessionState.NoCookie =>
    core.fmt.Formatter.write_str f (toStr "NoCookie")
  | access.SessionState.Unknown =>
    core.fmt.Formatter.write_str f (toStr "Unknown")
  | access.SessionState.Expired =>
    core.fmt.Formatter.write_str f (toStr "Expired")
  | access.SessionState.Valid => core.fmt.Formatter.write_str f (toStr "Valid")

/-- Trait implementation: [logbook_core::access::{impl core::fmt::Debug for logbook_core::access::SessionState}]
    Source: 'crates/logbook-core/src/access.rs', lines 17:9-17:14 -/
@[reducible]
def access.SessionState.Insts.CoreFmtDebug : core.fmt.Debug access.SessionState
  := {
  fmt := access.SessionState.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::access::{impl core::clone::Clone for logbook_core::access::SessionState}::clone]:
    Source: 'crates/logbook-core/src/access.rs', lines 17:16-17:21
    Visibility: public -/
def access.SessionState.Insts.CoreCloneClone.clone
  (self : access.SessionState) : Result access.SessionState := do
  ok self

/-- Trait implementation: [logbook_core::access::{impl core::clone::Clone for logbook_core::access::SessionState}]
    Source: 'crates/logbook-core/src/access.rs', lines 17:16-17:21 -/
@[reducible]
def access.SessionState.Insts.CoreCloneClone : core.clone.Clone
  access.SessionState := {
  clone := access.SessionState.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [logbook_core::access::{impl core::marker::Copy for logbook_core::access::SessionState}]
    Source: 'crates/logbook-core/src/access.rs', lines 17:23-17:27 -/
@[reducible]
def access.SessionState.Insts.CoreMarkerCopy : core.marker.Copy
  access.SessionState := {
  cloneInst := access.SessionState.Insts.CoreCloneClone
}

/-- Trait implementation: [logbook_core::access::{impl core::marker::StructuralPartialEq for logbook_core::access::SessionState}]
    Source: 'crates/logbook-core/src/access.rs', lines 17:29-17:38 -/
@[reducible]
def access.SessionState.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq access.SessionState := {
}

/-- [logbook_core::access::{impl core::cmp::PartialEq<logbook_core::access::SessionState> for logbook_core::access::SessionState}::eq]:
    Source: 'crates/logbook-core/src/access.rs', lines 17:29-17:38
    Visibility: public -/
def access.SessionState.Insts.CoreCmpPartialEqSessionState.eq
  (self : access.SessionState) (other : access.SessionState) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [logbook_core::access::{impl core::cmp::PartialEq<logbook_core::access::SessionState> for logbook_core::access::SessionState}]
    Source: 'crates/logbook-core/src/access.rs', lines 17:29-17:38 -/
@[reducible]
def access.SessionState.Insts.CoreCmpPartialEqSessionState : core.cmp.PartialEq
  access.SessionState access.SessionState := {
  eq := access.SessionState.Insts.CoreCmpPartialEqSessionState.eq
}

/-- Trait implementation: [logbook_core::access::{impl core::cmp::Eq for logbook_core::access::SessionState}]
    Source: 'crates/logbook-core/src/access.rs', lines 17:40-17:42 -/
@[reducible]
impl_def access.SessionState.Insts.CoreCmpEq : core.cmp.Eq access.SessionState
  := {
  partialEqInst := access.SessionState.Insts.CoreCmpPartialEqSessionState
  assert_fields_are_eq := core.cmp.Eq.assert_fields_are_eq.default
    access.SessionState.Insts.CoreCmpEq
}

/-- [logbook_core::access::{impl core::fmt::Debug for logbook_core::access::Decision}::fmt]:
    Source: 'crates/logbook-core/src/access.rs', lines 31:9-31:14
    Visibility: public -/
def access.Decision.Insts.CoreFmtDebug.fmt
  (self : access.Decision) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | access.Decision.Allow => core.fmt.Formatter.write_str f (toStr "Allow")
  | access.Decision.Unauthorized =>
    core.fmt.Formatter.write_str f (toStr "Unauthorized")

/-- Trait implementation: [logbook_core::access::{impl core::fmt::Debug for logbook_core::access::Decision}]
    Source: 'crates/logbook-core/src/access.rs', lines 31:9-31:14 -/
@[reducible]
def access.Decision.Insts.CoreFmtDebug : core.fmt.Debug access.Decision := {
  fmt := access.Decision.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::access::{impl core::clone::Clone for logbook_core::access::Decision}::clone]:
    Source: 'crates/logbook-core/src/access.rs', lines 31:16-31:21
    Visibility: public -/
def access.Decision.Insts.CoreCloneClone.clone
  (self : access.Decision) : Result access.Decision := do
  ok self

/-- Trait implementation: [logbook_core::access::{impl core::clone::Clone for logbook_core::access::Decision}]
    Source: 'crates/logbook-core/src/access.rs', lines 31:16-31:21 -/
@[reducible]
def access.Decision.Insts.CoreCloneClone : core.clone.Clone access.Decision
  := {
  clone := access.Decision.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [logbook_core::access::{impl core::marker::Copy for logbook_core::access::Decision}]
    Source: 'crates/logbook-core/src/access.rs', lines 31:23-31:27 -/
@[reducible]
def access.Decision.Insts.CoreMarkerCopy : core.marker.Copy access.Decision
  := {
  cloneInst := access.Decision.Insts.CoreCloneClone
}

/-- Trait implementation: [logbook_core::access::{impl core::marker::StructuralPartialEq for logbook_core::access::Decision}]
    Source: 'crates/logbook-core/src/access.rs', lines 31:29-31:38 -/
@[reducible]
def access.Decision.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq access.Decision := {
}

/-- [logbook_core::access::{impl core::cmp::PartialEq<logbook_core::access::Decision> for logbook_core::access::Decision}::eq]:
    Source: 'crates/logbook-core/src/access.rs', lines 31:29-31:38
    Visibility: public -/
def access.Decision.Insts.CoreCmpPartialEqDecision.eq
  (self : access.Decision) (other : access.Decision) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [logbook_core::access::{impl core::cmp::PartialEq<logbook_core::access::Decision> for logbook_core::access::Decision}]
    Source: 'crates/logbook-core/src/access.rs', lines 31:29-31:38 -/
@[reducible]
def access.Decision.Insts.CoreCmpPartialEqDecision : core.cmp.PartialEq
  access.Decision access.Decision := {
  eq := access.Decision.Insts.CoreCmpPartialEqDecision.eq
}

/-- Trait implementation: [logbook_core::access::{impl core::cmp::Eq for logbook_core::access::Decision}]
    Source: 'crates/logbook-core/src/access.rs', lines 31:40-31:42 -/
@[reducible]
impl_def access.Decision.Insts.CoreCmpEq : core.cmp.Eq access.Decision := {
  partialEqInst := access.Decision.Insts.CoreCmpPartialEqDecision
  assert_fields_are_eq := core.cmp.Eq.assert_fields_are_eq.default
    access.Decision.Insts.CoreCmpEq
}

/-- [logbook_core::access::authorize]:
    Source: 'crates/logbook-core/src/access.rs', lines 42:0-54:1
    Visibility: public -/
def access.authorize
  (level : access.Access) (state : access.SessionState) :
  Result access.Decision
  := do
  match level with
  | access.Access.Public => ok access.Decision.Allow
  | access.Access.Session => ok access.Decision.Allow
  | access.Access.Auth => ok access.Decision.Allow
  | access.Access.Owner =>
    match state with
    | access.SessionState.NoCookie => ok access.Decision.Unauthorized
    | access.SessionState.Unknown => ok access.Decision.Unauthorized
    | access.SessionState.Expired => ok access.Decision.Unauthorized
    | access.SessionState.Valid => ok access.Decision.Allow

/-- [logbook_core::csrf::lower]:
    Source: 'crates/logbook-core/src/csrf.rs', lines 7:0-9:1 -/
def csrf.lower (c : Std.U8) : Result Std.U8 := do
  if c >= 65#u8
  then if c <= 90#u8
       then c + 32#u8
       else ok c
  else ok c

/-- [logbook_core::csrf::is_space]:
    Source: 'crates/logbook-core/src/csrf.rs', lines 12:0-14:1 -/
def csrf.is_space (c : Std.U8) : Result Bool := do
  if c = 32#u8
  then ok true
  else ok (c = 9#u8)

/-- [logbook_core::csrf::skip_spaces]: loop body 0:
    Source: 'crates/logbook-core/src/csrf.rs', lines 19:4-26:1 -/
@[rust_loop_body]
def csrf.skip_spaces_loop.body
  (s : Slice Std.U8) (j : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i := Slice.len s
  if j < i
  then
    let i1 ← Slice.index_usize s j
    let b ← csrf.is_space i1
    if b
    then let j1 ← j + 1#usize
         ok (cont j1)
    else ok (done j)
  else ok (done j)

/-- [logbook_core::csrf::skip_spaces]: loop 0:
    Source: 'crates/logbook-core/src/csrf.rs', lines 19:4-26:1 -/
@[rust_loop]
def csrf.skip_spaces_loop
  (s : Slice Std.U8) (j : Std.Usize) : Result Std.Usize := do
  loop
    (fun j1 => csrf.skip_spaces_loop.body s j1)
    j

/-- [logbook_core::csrf::skip_spaces]:
    Source: 'crates/logbook-core/src/csrf.rs', lines 17:0-26:1 -/
@[reducible]
def csrf.skip_spaces
  (s : Slice Std.U8) (i : Std.Usize) : Result Std.Usize := do
  csrf.skip_spaces_loop s i

/-- [logbook_core::csrf::starts_with_lower]: loop body 0:
    Source: 'crates/logbook-core/src/csrf.rs', lines 35:4-42:1 -/
@[rust_loop_body]
def csrf.starts_with_lower_loop.body
  (s : Slice Std.U8) («at» : Std.Usize) (want : Slice Std.U8) (j : Std.Usize)
  :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i := Slice.len want
  if j < i
  then
    let i1 ← «at» + j
    let i2 ← Slice.index_usize s i1
    let i3 ← csrf.lower i2
    let i4 ← Slice.index_usize want j
    if i3 != i4
    then ok (done false)
    else let j1 ← j + 1#usize
         ok (cont j1)
  else ok (done true)

/-- [logbook_core::csrf::starts_with_lower]: loop 0:
    Source: 'crates/logbook-core/src/csrf.rs', lines 35:4-42:1 -/
@[rust_loop]
def csrf.starts_with_lower_loop
  (s : Slice Std.U8) («at» : Std.Usize) (want : Slice Std.U8) (j : Std.Usize)
  :
  Result Bool
  := do
  loop
    (fun j1 => csrf.starts_with_lower_loop.body s «at» want j1)
    j

/-- [logbook_core::csrf::starts_with_lower]:
    Source: 'crates/logbook-core/src/csrf.rs', lines 30:0-42:1 -/
def csrf.starts_with_lower
  (s : Slice Std.U8) («at» : Std.Usize) (want : Slice Std.U8) :
  Result Bool
  := do
  let i := Slice.len s
  if «at» > i
  then ok false
  else
    let i1 := Slice.len s
    let i2 ← i1 - «at»
    let i3 := Slice.len want
    if i2 < i3
    then ok false
    else csrf.starts_with_lower_loop s «at» want 0#usize

/-- [logbook_core::csrf::is_json]:
    Source: 'crates/logbook-core/src/csrf.rs', lines 50:0-57:1
    Visibility: public -/
def csrf.is_json (content_type : Slice Std.U8) : Result Bool := do
  let start ← csrf.skip_spaces content_type 0#usize
  let s ←
    lift (Array.to_slice
      (Array.make 16#usize [
        97#u8, 112#u8, 112#u8, 108#u8, 105#u8, 99#u8, 97#u8, 116#u8, 105#u8,
        111#u8, 110#u8, 47#u8, 106#u8, 115#u8, 111#u8, 110#u8
        ]))
  let b ← csrf.starts_with_lower content_type start s
  if b
  then
    let i ← start + 16#usize
    let «end» ← csrf.skip_spaces content_type i
    let i1 := Slice.len content_type
    if «end» = i1
    then ok true
    else let i2 ← Slice.index_usize content_type «end»
         ok (i2 = 59#u8)
  else ok false

/-- [logbook_core::csrf::is_multipart_form]:
    Source: 'crates/logbook-core/src/csrf.rs', lines 61:0-63:1
    Visibility: public -/
def csrf.is_multipart_form (content_type : Slice Std.U8) : Result Bool := do
  let s ←
    lift (Array.to_slice
      (Array.make 19#usize [
        109#u8, 117#u8, 108#u8, 116#u8, 105#u8, 112#u8, 97#u8, 114#u8, 116#u8,
        47#u8, 102#u8, 111#u8, 114#u8, 109#u8, 45#u8, 100#u8, 97#u8, 116#u8,
        97#u8
        ]))
  csrf.starts_with_lower content_type 0#usize s

/-- [logbook_core::csrf::write_allowed]:
    Source: 'crates/logbook-core/src/csrf.rs', lines 77:0-94:1
    Visibility: public -/
def csrf.write_allowed
  (is_read : Bool) (origin_matches : Bool) (has_body : Bool)
  (content_type : Slice Std.U8) (is_upload_path : Bool) :
  Result Bool
  := do
  if is_read
  then ok true
  else
    if origin_matches
    then
      if has_body
      then
        let b ← csrf.is_json content_type
        if b
        then ok true
        else
          if is_upload_path
          then csrf.is_multipart_form content_type
          else ok false
      else ok true
    else ok false

/-- [logbook_core::html::escape_html]: loop body 0:
    Source: 'crates/logbook-core/src/html.rs', lines 14:4-49:5
    Visibility: public -/
@[rust_loop_body]
def html.escape_html_loop.body
  (s : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len s
  if i < i1
  then
    let c ← Slice.index_usize s i
    let out1 ←
      if c = 38#u8
      then
        do
        let out2 ← alloc.vec.Vec.push out 38#u8
        let out3 ← alloc.vec.Vec.push out2 97#u8
        let out4 ← alloc.vec.Vec.push out3 109#u8
        let out5 ← alloc.vec.Vec.push out4 112#u8
        alloc.vec.Vec.push out5 59#u8
      else
        if c = 60#u8
        then
          do
          let out2 ← alloc.vec.Vec.push out 38#u8
          let out3 ← alloc.vec.Vec.push out2 108#u8
          let out4 ← alloc.vec.Vec.push out3 116#u8
          alloc.vec.Vec.push out4 59#u8
        else
          if c = 62#u8
          then
            do
            let out2 ← alloc.vec.Vec.push out 38#u8
            let out3 ← alloc.vec.Vec.push out2 103#u8
            let out4 ← alloc.vec.Vec.push out3 116#u8
            alloc.vec.Vec.push out4 59#u8
          else
            if c = 34#u8
            then
              do
              let out2 ← alloc.vec.Vec.push out 38#u8
              let out3 ← alloc.vec.Vec.push out2 113#u8
              let out4 ← alloc.vec.Vec.push out3 117#u8
              let out5 ← alloc.vec.Vec.push out4 111#u8
              let out6 ← alloc.vec.Vec.push out5 116#u8
              alloc.vec.Vec.push out6 59#u8
            else
              if c = 39#u8
              then
                do
                let out2 ← alloc.vec.Vec.push out 38#u8
                let out3 ← alloc.vec.Vec.push out2 35#u8
                let out4 ← alloc.vec.Vec.push out3 51#u8
                let out5 ← alloc.vec.Vec.push out4 57#u8
                alloc.vec.Vec.push out5 59#u8
              else alloc.vec.Vec.push out c
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [logbook_core::html::escape_html]: loop 0:
    Source: 'crates/logbook-core/src/html.rs', lines 14:4-49:5
    Visibility: public -/
@[rust_loop]
def html.escape_html_loop
  (s : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => html.escape_html_loop.body s out1 i1)
    (out, i)

/-- [logbook_core::html::escape_html]:
    Source: 'crates/logbook-core/src/html.rs', lines 11:0-51:1
    Visibility: public -/
@[reducible]
def html.escape_html (s : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  html.escape_html_loop s (alloc.vec.Vec.new Std.U8) 0#usize

/-- [logbook_core::ip::{impl core::fmt::Debug for logbook_core::ip::ClientAddr}::fmt]:
    Source: 'crates/logbook-core/src/ip.rs', lines 7:9-7:14
    Visibility: public -/
def ip.ClientAddr.Insts.CoreFmtDebug.fmt
  (self : ip.ClientAddr) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | ip.ClientAddr.Peer => core.fmt.Formatter.write_str f (toStr "Peer")
  | ip.ClientAddr.Hop __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Hop") __self_01

/-- Trait implementation: [logbook_core::ip::{impl core::fmt::Debug for logbook_core::ip::ClientAddr}]
    Source: 'crates/logbook-core/src/ip.rs', lines 7:9-7:14 -/
@[reducible]
def ip.ClientAddr.Insts.CoreFmtDebug : core.fmt.Debug ip.ClientAddr := {
  fmt := ip.ClientAddr.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::ip::{impl core::clone::Clone for logbook_core::ip::ClientAddr}::clone]:
    Source: 'crates/logbook-core/src/ip.rs', lines 7:16-7:21
    Visibility: public -/
def ip.ClientAddr.Insts.CoreCloneClone.clone
  (self : ip.ClientAddr) : Result ip.ClientAddr := do
  ok self

/-- Trait implementation: [logbook_core::ip::{impl core::clone::Clone for logbook_core::ip::ClientAddr}]
    Source: 'crates/logbook-core/src/ip.rs', lines 7:16-7:21 -/
@[reducible]
def ip.ClientAddr.Insts.CoreCloneClone : core.clone.Clone ip.ClientAddr := {
  clone := ip.ClientAddr.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [logbook_core::ip::{impl core::marker::Copy for logbook_core::ip::ClientAddr}]
    Source: 'crates/logbook-core/src/ip.rs', lines 7:23-7:27 -/
@[reducible]
def ip.ClientAddr.Insts.CoreMarkerCopy : core.marker.Copy ip.ClientAddr := {
  cloneInst := ip.ClientAddr.Insts.CoreCloneClone
}

/-- Trait implementation: [logbook_core::ip::{impl core::marker::StructuralPartialEq for logbook_core::ip::ClientAddr}]
    Source: 'crates/logbook-core/src/ip.rs', lines 7:29-7:38 -/
@[reducible]
def ip.ClientAddr.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ip.ClientAddr := {
}

/-- [logbook_core::ip::{impl core::cmp::PartialEq<logbook_core::ip::ClientAddr> for logbook_core::ip::ClientAddr}::eq]:
    Source: 'crates/logbook-core/src/ip.rs', lines 7:29-7:38
    Visibility: public -/
def ip.ClientAddr.Insts.CoreCmpPartialEqClientAddr.eq
  (self : ip.ClientAddr) (other : ip.ClientAddr) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | ip.ClientAddr.Peer => ok true
    | ip.ClientAddr.Hop __self_0 =>
      match other with
      | ip.ClientAddr.Peer => ok true
      | ip.ClientAddr.Hop __arg1_0 =>
        lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
  else ok false

/-- Trait implementation: [logbook_core::ip::{impl core::cmp::PartialEq<logbook_core::ip::ClientAddr> for logbook_core::ip::ClientAddr}]
    Source: 'crates/logbook-core/src/ip.rs', lines 7:29-7:38 -/
@[reducible]
def ip.ClientAddr.Insts.CoreCmpPartialEqClientAddr : core.cmp.PartialEq
  ip.ClientAddr ip.ClientAddr := {
  eq := ip.ClientAddr.Insts.CoreCmpPartialEqClientAddr.eq
}

/-- [logbook_core::ip::{impl core::cmp::Eq for logbook_core::ip::ClientAddr}::assert_fields_are_eq]:
    Source: 'crates/logbook-core/src/ip.rs', lines 7:40-7:42
    Visibility: public -/
def ip.ClientAddr.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ip.ClientAddr) : Result Unit := do
  ok ()

/-- Trait implementation: [logbook_core::ip::{impl core::cmp::Eq for logbook_core::ip::ClientAddr}]
    Source: 'crates/logbook-core/src/ip.rs', lines 7:40-7:42 -/
@[reducible]
def ip.ClientAddr.Insts.CoreCmpEq : core.cmp.Eq ip.ClientAddr := {
  partialEqInst := ip.ClientAddr.Insts.CoreCmpPartialEqClientAddr
  assert_fields_are_eq := ip.ClientAddr.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [logbook_core::ip::client_addr]: loop body 0:
    Source: 'crates/logbook-core/src/ip.rs', lines 29:4-36:1
    Visibility: public -/
@[rust_loop_body]
def ip.client_addr_loop.body
  (hop_trusted : Slice Bool) (i : Std.Usize) :
  Result (ControlFlow Std.Usize ip.ClientAddr)
  := do
  if i > 0#usize
  then
    let i1 ← i - 1#usize
    let b ← Slice.index_usize hop_trusted i1
    if b
    then ok (cont i1)
    else ok (done (ip.ClientAddr.Hop i1))
  else ok (done ip.ClientAddr.Peer)

/-- [logbook_core::ip::client_addr]: loop 0:
    Source: 'crates/logbook-core/src/ip.rs', lines 29:4-36:1
    Visibility: public -/
@[rust_loop]
def ip.client_addr_loop
  (hop_trusted : Slice Bool) (i : Std.Usize) : Result ip.ClientAddr := do
  loop
    (fun i1 => ip.client_addr_loop.body hop_trusted i1)
    i

/-- [logbook_core::ip::client_addr]:
    Source: 'crates/logbook-core/src/ip.rs', lines 24:0-36:1
    Visibility: public -/
def ip.client_addr
  (peer_trusted : Bool) (hop_trusted : Slice Bool) : Result ip.ClientAddr := do
  if peer_trusted
  then let i := Slice.len hop_trusted
       ip.client_addr_loop hop_trusted i
  else ok ip.ClientAddr.Peer

/-- [logbook_core::media::is_lower_hex]:
    Source: 'crates/logbook-core/src/media.rs', lines 7:0-9:1 -/
def media.is_lower_hex (c : Std.U8) : Result Bool := do
  if c >= 48#u8
  then
    if c <= 57#u8
    then ok true
    else if c >= 97#u8
         then ok (c <= 102#u8)
         else ok false
  else if c >= 97#u8
       then ok (c <= 102#u8)
       else ok false

/-- [logbook_core::media::tail_is]: loop body 0:
    Source: 'crates/logbook-core/src/media.rs', lines 17:4-24:1 -/
@[rust_loop_body]
def media.tail_is_loop.body
  (key : Slice Std.U8) («at» : Std.Usize) (ext : Slice Std.U8)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len ext
  if i < i1
  then
    let i2 ← «at» + i
    let i3 ← Slice.index_usize key i2
    let i4 ← Slice.index_usize ext i
    if i3 != i4
    then ok (done false)
    else let i5 ← i + 1#usize
         ok (cont i5)
  else ok (done true)

/-- [logbook_core::media::tail_is]: loop 0:
    Source: 'crates/logbook-core/src/media.rs', lines 17:4-24:1 -/
@[rust_loop]
def media.tail_is_loop
  (key : Slice Std.U8) («at» : Std.Usize) (ext : Slice Std.U8)
  (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => media.tail_is_loop.body key «at» ext i1)
    i

/-- [logbook_core::media::tail_is]:
    Source: 'crates/logbook-core/src/media.rs', lines 12:0-24:1 -/
def media.tail_is
  (key : Slice Std.U8) («at» : Std.Usize) (ext : Slice Std.U8) :
  Result Bool
  := do
  let i := Slice.len key
  let i1 := Slice.len ext
  let i2 ← «at» + i1
  if i != i2
  then ok false
  else media.tail_is_loop key «at» ext 0#usize

/-- [logbook_core::media::media_key_ok]: loop body 0:
    Source: 'crates/logbook-core/src/media.rs', lines 34:4-45:1
    Visibility: public -/
@[rust_loop_body]
def media.media_key_ok_loop.body
  (key : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if i < 64#usize
  then
    let i1 ← Slice.index_usize key i
    let b ← media.is_lower_hex i1
    if b
    then let i2 ← i + 1#usize
         ok (cont i2)
    else ok (done false)
  else
    let i1 ← Slice.index_usize key 64#usize
    if i1 = 46#u8
    then
      let s ←
        lift (Array.to_slice (Array.make 3#usize [ 112#u8, 110#u8, 103#u8 ]))
      let b ← media.tail_is key 65#usize s
      if b
      then ok (done true)
      else
        let s1 ←
          lift (Array.to_slice (Array.make 3#usize [ 106#u8, 112#u8, 103#u8 ]))
        let b1 ← media.tail_is key 65#usize s1
        if b1
        then ok (done true)
        else
          let s2 ←
            lift (Array.to_slice
              (Array.make 3#usize [ 103#u8, 105#u8, 102#u8 ]))
          let b2 ← media.tail_is key 65#usize s2
          if b2
          then ok (done true)
          else
            let s3 ←
              lift (Array.to_slice
                (Array.make 4#usize [ 119#u8, 101#u8, 98#u8, 112#u8 ]))
            let b3 ← media.tail_is key 65#usize s3
            ok (done b3)
    else ok (done false)

/-- [logbook_core::media::media_key_ok]: loop 0:
    Source: 'crates/logbook-core/src/media.rs', lines 34:4-45:1
    Visibility: public -/
@[rust_loop]
def media.media_key_ok_loop
  (key : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => media.media_key_ok_loop.body key i1)
    i

/-- [logbook_core::media::media_key_ok]:
    Source: 'crates/logbook-core/src/media.rs', lines 29:0-45:1
    Visibility: public -/
def media.media_key_ok (key : Slice Std.U8) : Result Bool := do
  let i := Slice.len key
  if i < 68#usize
  then ok false
  else media.media_key_ok_loop key 0#usize

/-- [logbook_core::post::{impl core::fmt::Debug for logbook_core::post::State}::fmt]:
    Source: 'crates/logbook-core/src/post.rs', lines 7:9-7:14
    Visibility: public -/
def post.State.Insts.CoreFmtDebug.fmt
  (self : post.State) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | post.State.Draft => core.fmt.Formatter.write_str f (toStr "Draft")
  | post.State.Private => core.fmt.Formatter.write_str f (toStr "Private")
  | post.State.Public => core.fmt.Formatter.write_str f (toStr "Public")

/-- Trait implementation: [logbook_core::post::{impl core::fmt::Debug for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:9-7:14 -/
@[reducible]
def post.State.Insts.CoreFmtDebug : core.fmt.Debug post.State := {
  fmt := post.State.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::post::{impl core::fmt::Debug for logbook_core::post::Post}::fmt]:
    Source: 'crates/logbook-core/src/post.rs', lines 21:9-21:14
    Visibility: public -/
def post.Post.Insts.CoreFmtDebug.fmt
  (self : post.Post) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.id
  let dyn1 := Dyn.mk _ post.State.Insts.CoreFmtDebug self.state
  let dyn2 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.topic
  let dyn3 := Dyn.mk _ core.fmt.DebugU32 self.word_count
  let dyn4 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.slug
  let dyn5 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.title
  let dyn6 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.summary
  let dyn7 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.tags
  let dyn8 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.body_html
  let dyn9 :=
    Dyn.mk _ (core.option.Option.Insts.CoreFmtDebug (core.fmt.DebugVec
      core.fmt.DebugU8)) self.published_at
  let dyn10 :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec core.fmt.DebugU8))
      self.updated_at
  let values :=
    Array.to_slice
      (Array.make 11#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 11#usize [
        toStr "id", toStr "state", toStr "topic", toStr "word_count", toStr
        "slug", toStr "title", toStr "summary", toStr "tags", toStr
        "body_html", toStr "published_at", toStr "updated_at"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "Post") s values

/-- Trait implementation: [logbook_core::post::{impl core::fmt::Debug for logbook_core::post::Post}]
    Source: 'crates/logbook-core/src/post.rs', lines 21:9-21:14 -/
@[reducible]
def post.Post.Insts.CoreFmtDebug : core.fmt.Debug post.Post := {
  fmt := post.Post.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::policy::{impl core::fmt::Debug for logbook_core::policy::PublicPost}::fmt]:
    Source: 'crates/logbook-core/src/policy.rs', lines 12:9-12:14
    Visibility: public -/
def policy.PublicPost.Insts.CoreFmtDebug.fmt
  (self : policy.PublicPost) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared post.Post.Insts.CoreFmtDebug) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "PublicPost") dyn

/-- Trait implementation: [logbook_core::policy::{impl core::fmt::Debug for logbook_core::policy::PublicPost}]
    Source: 'crates/logbook-core/src/policy.rs', lines 12:9-12:14 -/
@[reducible]
def policy.PublicPost.Insts.CoreFmtDebug : core.fmt.Debug policy.PublicPost
  := {
  fmt := policy.PublicPost.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::post::clone_opt]:
    Source: 'crates/logbook-core/src/post.rs', lines 40:0-45:1 -/
def post.clone_opt
  (v : Option (alloc.vec.Vec Std.U8)) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  match v with
  | none => ok none
  | some b =>
    let v1 ← alloc.vec.CloneVec.clone core.clone.CloneU8 b
    ok (some v1)

/-- [logbook_core::post::{impl core::clone::Clone for logbook_core::post::Post}::clone]:
    Source: 'crates/logbook-core/src/post.rs', lines 48:4-62:5
    Visibility: public -/
def post.Post.Insts.CoreCloneClone.clone
  (self : post.Post) : Result post.Post := do
  let v ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.topic
  let v1 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.slug
  let v2 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.title
  let v3 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.summary
  let v4 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.tags
  let v5 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.body_html
  let o ← post.clone_opt self.published_at
  let v6 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.updated_at
  ok
    {
      self
        with
        topic := v,
        slug := v1,
        title := v2,
        summary := v3,
        tags := v4,
        body_html := v5,
        published_at := o,
        updated_at := v6
    }

/-- [logbook_core::policy::{impl core::clone::Clone for logbook_core::policy::PublicPost}::clone]:
    Source: 'crates/logbook-core/src/policy.rs', lines 12:16-12:21
    Visibility: public -/
def policy.PublicPost.Insts.CoreCloneClone.clone
  (self : policy.PublicPost) : Result policy.PublicPost := do
  let p ← post.Post.Insts.CoreCloneClone.clone self
  ok p

/-- Trait implementation: [logbook_core::policy::{impl core::clone::Clone for logbook_core::policy::PublicPost}]
    Source: 'crates/logbook-core/src/policy.rs', lines 12:16-12:21 -/
@[reducible]
def policy.PublicPost.Insts.CoreCloneClone : core.clone.Clone policy.PublicPost
  := {
  clone := policy.PublicPost.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [logbook_core::policy::{impl core::marker::StructuralPartialEq for logbook_core::policy::PublicPost}]
    Source: 'crates/logbook-core/src/policy.rs', lines 12:23-12:32 -/
@[reducible]
def policy.PublicPost.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq policy.PublicPost := {
}

/-- [logbook_core::post::{impl core::cmp::PartialEq<logbook_core::post::State> for logbook_core::post::State}::eq]:
    Source: 'crates/logbook-core/src/post.rs', lines 7:29-7:38
    Visibility: public -/
def post.State.Insts.CoreCmpPartialEqState.eq
  (self : post.State) (other : post.State) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [logbook_core::post::{impl core::cmp::PartialEq<logbook_core::post::Post> for logbook_core::post::Post}::eq]:
    Source: 'crates/logbook-core/src/post.rs', lines 21:16-21:25
    Visibility: public -/
def post.Post.Insts.CoreCmpPartialEqPost.eq
  (self : post.Post) (other : post.Post) : Result Bool := do
  if self.id = other.id
  then
    if self.word_count = other.word_count
    then
      let b ←
        post.State.Insts.CoreCmpPartialEqState.eq self.state other.state
      if b
      then
        let b1 ←
          alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8 self.topic
            other.topic
        if b1
        then
          let b2 ←
            alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8 
              self.slug other.slug
          if b2
          then
            let b3 ←
              alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8
                self.title other.title
            if b3
            then
              let b4 ←
                alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8
                  self.summary other.summary
              if b4
              then
                let b5 ←
                  alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8
                    self.tags other.tags
                if b5
                then
                  let b6 ←
                    alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8
                      self.body_html other.body_html
                  if b6
                  then
                    let b7 ←
                      core.option.Option.Insts.CoreCmpPartialEqOption.eq
                        (core.cmp.PartialEqVec core.cmp.PartialEqU8)
                        self.published_at other.published_at
                    if b7
                    then
                      alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8
                        self.updated_at other.updated_at
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- [logbook_core::policy::{impl core::cmp::PartialEq<logbook_core::policy::PublicPost> for logbook_core::policy::PublicPost}::eq]:
    Source: 'crates/logbook-core/src/policy.rs', lines 12:23-12:32
    Visibility: public -/
def policy.PublicPost.Insts.CoreCmpPartialEqPublicPost.eq
  (self : policy.PublicPost) (other : policy.PublicPost) : Result Bool := do
  post.Post.Insts.CoreCmpPartialEqPost.eq self other

/-- Trait implementation: [logbook_core::policy::{impl core::cmp::PartialEq<logbook_core::policy::PublicPost> for logbook_core::policy::PublicPost}]
    Source: 'crates/logbook-core/src/policy.rs', lines 12:23-12:32 -/
@[reducible]
def policy.PublicPost.Insts.CoreCmpPartialEqPublicPost : core.cmp.PartialEq
  policy.PublicPost policy.PublicPost := {
  eq := policy.PublicPost.Insts.CoreCmpPartialEqPublicPost.eq
}

/-- [logbook_core::policy::{impl core::cmp::Eq for logbook_core::policy::PublicPost}::assert_fields_are_eq]:
    Source: 'crates/logbook-core/src/policy.rs', lines 12:34-12:36
    Visibility: public -/
def policy.PublicPost.Insts.CoreCmpEq.assert_fields_are_eq
  (self : policy.PublicPost) : Result Unit := do
  ok ()

/-- Trait implementation: [logbook_core::policy::{impl core::cmp::Eq for logbook_core::policy::PublicPost}]
    Source: 'crates/logbook-core/src/policy.rs', lines 12:34-12:36 -/
@[reducible]
def policy.PublicPost.Insts.CoreCmpEq : core.cmp.Eq policy.PublicPost := {
  partialEqInst := policy.PublicPost.Insts.CoreCmpPartialEqPublicPost
  assert_fields_are_eq :=
    policy.PublicPost.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [logbook_core::policy::{logbook_core::policy::PublicPost}::post]:
    Source: 'crates/logbook-core/src/policy.rs', lines 18:4-20:5
    Visibility: public -/
def policy.PublicPost.post (self : policy.PublicPost) : Result post.Post := do
  ok self

/-- [logbook_core::policy::reveal]:
    Source: 'crates/logbook-core/src/policy.rs', lines 26:0-31:1
    Visibility: public -/
def policy.reveal (p : post.Post) : Result (Option policy.PublicPost) := do
  match p.state with
  | post.State.Draft => ok none
  | post.State.Private => ok none
  | post.State.Public => ok (some p)

/-- [logbook_core::policy::filter_public]: loop body 0:
    Source: 'crates/logbook-core/src/policy.rs', lines 38:4-43:5
    Visibility: public -/
@[rust_loop_body]
def policy.filter_public_loop.body
  (ps : Slice post.Post) (out : alloc.vec.Vec policy.PublicPost)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec policy.PublicPost) × Std.Usize)
    (alloc.vec.Vec policy.PublicPost))
  := do
  let i1 := Slice.len ps
  if i < i1
  then
    let p ← Slice.index_usize ps i
    let p1 ← post.Post.Insts.CoreCloneClone.clone p
    let o ← policy.reveal p1
    let out1 ←
      match o with
      | none => ok out
      | some q => alloc.vec.Vec.push out q
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [logbook_core::policy::filter_public]: loop 0:
    Source: 'crates/logbook-core/src/policy.rs', lines 38:4-43:5
    Visibility: public -/
@[rust_loop]
def policy.filter_public_loop
  (ps : Slice post.Post) (out : alloc.vec.Vec policy.PublicPost)
  (i : Std.Usize) :
  Result (alloc.vec.Vec policy.PublicPost)
  := do
  loop
    (fun (out1, i1) => policy.filter_public_loop.body ps out1 i1)
    (out, i)

/-- [logbook_core::policy::filter_public]:
    Source: 'crates/logbook-core/src/policy.rs', lines 35:0-45:1
    Visibility: public -/
@[reducible]
def policy.filter_public
  (ps : Slice post.Post) : Result (alloc.vec.Vec policy.PublicPost) := do
  policy.filter_public_loop ps (alloc.vec.Vec.new policy.PublicPost) 0#usize

/-- [logbook_core::post::WORDS_PER_MINUTE]
    Source: 'crates/logbook-core/src/post.rs', lines 4:0-4:38
    Visibility: public -/
@[global_simps, irreducible] def post.WORDS_PER_MINUTE : Std.U32 := 220#u32

/-- [logbook_core::post::{impl core::clone::Clone for logbook_core::post::State}::clone]:
    Source: 'crates/logbook-core/src/post.rs', lines 7:16-7:21
    Visibility: public -/
def post.State.Insts.CoreCloneClone.clone
  (self : post.State) : Result post.State := do
  ok self

/-- Trait implementation: [logbook_core::post::{impl core::clone::Clone for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:16-7:21 -/
@[reducible]
def post.State.Insts.CoreCloneClone : core.clone.Clone post.State := {
  clone := post.State.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [logbook_core::post::{impl core::marker::Copy for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:23-7:27 -/
@[reducible]
def post.State.Insts.CoreMarkerCopy : core.marker.Copy post.State := {
  cloneInst := post.State.Insts.CoreCloneClone
}

/-- Trait implementation: [logbook_core::post::{impl core::marker::StructuralPartialEq for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:29-7:38 -/
@[reducible]
def post.State.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq post.State := {
}

/-- Trait implementation: [logbook_core::post::{impl core::cmp::PartialEq<logbook_core::post::State> for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:29-7:38 -/
@[reducible]
def post.State.Insts.CoreCmpPartialEqState : core.cmp.PartialEq post.State
  post.State := {
  eq := post.State.Insts.CoreCmpPartialEqState.eq
}

/-- Trait implementation: [logbook_core::post::{impl core::cmp::Eq for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:40-7:42 -/
@[reducible]
impl_def post.State.Insts.CoreCmpEq : core.cmp.Eq post.State := {
  partialEqInst := post.State.Insts.CoreCmpPartialEqState
  assert_fields_are_eq := core.cmp.Eq.assert_fields_are_eq.default
    post.State.Insts.CoreCmpEq
}

/-- Trait implementation: [logbook_core::post::{impl core::marker::StructuralPartialEq for logbook_core::post::Post}]
    Source: 'crates/logbook-core/src/post.rs', lines 21:16-21:25 -/
@[reducible]
def post.Post.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq post.Post := {
}

/-- Trait implementation: [logbook_core::post::{impl core::cmp::PartialEq<logbook_core::post::Post> for logbook_core::post::Post}]
    Source: 'crates/logbook-core/src/post.rs', lines 21:16-21:25 -/
@[reducible]
def post.Post.Insts.CoreCmpPartialEqPost : core.cmp.PartialEq post.Post
  post.Post := {
  eq := post.Post.Insts.CoreCmpPartialEqPost.eq
}

/-- [logbook_core::post::{impl core::cmp::Eq for logbook_core::post::Post}::assert_fields_are_eq]:
    Source: 'crates/logbook-core/src/post.rs', lines 21:27-21:29
    Visibility: public -/
def post.Post.Insts.CoreCmpEq.assert_fields_are_eq
  (self : post.Post) : Result Unit := do
  ok ()

/-- Trait implementation: [logbook_core::post::{impl core::cmp::Eq for logbook_core::post::Post}]
    Source: 'crates/logbook-core/src/post.rs', lines 21:27-21:29 -/
@[reducible]
def post.Post.Insts.CoreCmpEq : core.cmp.Eq post.Post := {
  partialEqInst := post.Post.Insts.CoreCmpPartialEqPost
  assert_fields_are_eq := post.Post.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- Trait implementation: [logbook_core::post::{impl core::clone::Clone for logbook_core::post::Post}]
    Source: 'crates/logbook-core/src/post.rs', lines 47:0-63:1 -/
@[reducible]
def post.Post.Insts.CoreCloneClone : core.clone.Clone post.Post := {
  clone := post.Post.Insts.CoreCloneClone.clone
}

/-- [logbook_core::post::reading_minutes]:
    Source: 'crates/logbook-core/src/post.rs', lines 68:0-73:1
    Visibility: public -/
def post.reading_minutes (words : Std.U32) : Result Std.U32 := do
  let full ← words / post.WORDS_PER_MINUTE
  let rest ← words % post.WORDS_PER_MINUTE
  let minutes ← if rest = 0#u32
                  then ok full
                  else full + 1#u32
  if minutes = 0#u32
  then ok 1#u32
  else ok minutes

/-- [logbook_core::session::SETUP_TOKEN_SECONDS]
    Source: 'crates/logbook-core/src/session.rs', lines 8:0-8:41
    Visibility: public -/
@[global_simps, irreducible]
def session.SETUP_TOKEN_SECONDS : Std.I64 := 900#i64

/-- [logbook_core::session::session_valid]:
    Source: 'crates/logbook-core/src/session.rs', lines 12:0-14:1
    Visibility: public -/
def session.session_valid
  (now : Std.I64) (expires_at : Std.I64) : Result Bool := do
  ok (now < expires_at)

/-- [logbook_core::session::setup_token_usable]:
    Source: 'crates/logbook-core/src/session.rs', lines 19:0-21:1
    Visibility: public -/
def session.setup_token_usable
  (now : Std.I64) (expires_at : Std.I64) (used : Bool) : Result Bool := do
  if used
  then ok false
  else ok (now < expires_at)

/-- [logbook_core::session::setup_token_expiry]:
    Source: 'crates/logbook-core/src/session.rs', lines 26:0-32:1
    Visibility: public -/
def session.setup_token_expiry (now : Std.I64) : Result Std.I64 := do
  let i ← core.num.I64.MAX - session.SETUP_TOKEN_SECONDS
  if now > i
  then ok core.num.I64.MAX
  else now + session.SETUP_TOKEN_SECONDS

/-- [logbook_core::slug::SLUG_MAX]
    Source: 'crates/logbook-core/src/slug.rs', lines 7:0-7:31
    Visibility: public -/
@[global_simps, irreducible] def slug.SLUG_MAX : Std.Usize := 80#usize

/-- [logbook_core::slug::lower]:
    Source: 'crates/logbook-core/src/slug.rs', lines 11:0-13:1 -/
def slug.lower (c : Std.U8) : Result Std.U8 := do
  if c >= 65#u8
  then if c <= 90#u8
       then c + 32#u8
       else ok c
  else ok c

/-- [logbook_core::slug::is_slug_char]:
    Source: 'crates/logbook-core/src/slug.rs', lines 15:0-17:1 -/
def slug.is_slug_char (c : Std.U8) : Result Bool := do
  if c >= 97#u8
  then
    if c <= 122#u8
    then ok true
    else if c >= 48#u8
         then ok (c <= 57#u8)
         else ok false
  else if c >= 48#u8
       then ok (c <= 57#u8)
       else ok false

/-- [logbook_core::slug::fallback]: loop body 0:
    Source: 'crates/logbook-core/src/slug.rs', lines 23:4-31:5 -/
@[rust_loop_body]
def slug.fallback_loop0.body
  (digits : alloc.vec.Vec Std.U8) (n : Std.U64) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.U64) (alloc.vec.Vec
    Std.U8))
  := do
  let i ← n % 10#u64
  let i1 ← lift (UScalar.cast .U8 i)
  let i2 ← 48#u8 + i1
  let digits1 ← alloc.vec.Vec.push digits i2
  let n1 ← n / 10#u64
  if n1 = 0#u64
  then ok (done digits1)
  else ok (cont (digits1, n1))

/-- [logbook_core::slug::fallback]: loop 0:
    Source: 'crates/logbook-core/src/slug.rs', lines 23:4-31:5 -/
@[rust_loop]
def slug.fallback_loop0
  (digits : alloc.vec.Vec Std.U8) (n : Std.U64) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (digits1, n1) => slug.fallback_loop0.body digits1 n1)
    (digits, n)

/-- [logbook_core::slug::fallback]: loop body 1:
    Source: 'crates/logbook-core/src/slug.rs', lines 34:4-37:5 -/
@[rust_loop_body]
def slug.fallback_loop1.body
  (digits : alloc.vec.Vec Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i > 0#usize
  then
    let i1 ← i - 1#usize
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8) digits
        i1
    let out1 ← alloc.vec.Vec.push out i2
    ok (cont (out1, i1))
  else ok (done out)

/-- [logbook_core::slug::fallback]: loop 1:
    Source: 'crates/logbook-core/src/slug.rs', lines 34:4-37:5 -/
@[rust_loop]
def slug.fallback_loop1
  (digits : alloc.vec.Vec Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => slug.fallback_loop1.body digits out1 i1)
    (out, i)

/-- [logbook_core::slug::fallback]:
    Source: 'crates/logbook-core/src/slug.rs', lines 20:0-39:1 -/
def slug.fallback (id : Std.U64) : Result (alloc.vec.Vec Std.U8) := do
  let digits ← slug.fallback_loop0 (alloc.vec.Vec.new Std.U8) id
  let s ←
    lift (Array.to_slice
      (Array.make 5#usize [ 112#u8, 111#u8, 115#u8, 116#u8, 45#u8 ]))
  let out ← alloc.slice.Slice.to_vec core.clone.CloneU8 s
  let i := alloc.vec.Vec.len digits
  slug.fallback_loop1 digits out i

/-- [logbook_core::slug::make_slug]: loop body 0:
    Source: 'crates/logbook-core/src/slug.rs', lines 54:4-72:5
    Visibility: public -/
@[rust_loop_body]
def slug.make_slug_loop.body
  (title : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (gap : Bool)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Bool × Std.Usize)
    (alloc.vec.Vec Std.U8))
  := do
  let i1 := Slice.len title
  if i < i1
  then
    let i2 ← Slice.index_usize title i
    let c ← slug.lower i2
    let b ← slug.is_slug_char c
    if b
    then
      if gap
      then
        let i3 := alloc.vec.Vec.len out
        if i3 > 0#usize
        then
          let i4 := alloc.vec.Vec.len out
          let i5 ← i4 + 2#usize
          if i5 > slug.SLUG_MAX
          then ok (done out)
          else
            let out1 ← alloc.vec.Vec.push out 45#u8
            let i6 := alloc.vec.Vec.len out1
            let i7 ← i6 + 1#usize
            if i7 > slug.SLUG_MAX
            then ok (done out1)
            else
              let out2 ← alloc.vec.Vec.push out1 c
              let i8 ← i + 1#usize
              ok (cont (out2, false, i8))
        else
          let i4 := alloc.vec.Vec.len out
          let i5 ← i4 + 1#usize
          if i5 > slug.SLUG_MAX
          then ok (done out)
          else
            let out1 ← alloc.vec.Vec.push out c
            let i6 ← i + 1#usize
            ok (cont (out1, false, i6))
      else
        let i3 := alloc.vec.Vec.len out
        let i4 ← i3 + 1#usize
        if i4 > slug.SLUG_MAX
        then ok (done out)
        else
          let out1 ← alloc.vec.Vec.push out c
          let i5 ← i + 1#usize
          ok (cont (out1, false, i5))
    else
      let gap1 ← if c != 39#u8
                   then ok true
                   else ok gap
      let i3 ← i + 1#usize
      ok (cont (out, gap1, i3))
  else ok (done out)

/-- [logbook_core::slug::make_slug]: loop 0:
    Source: 'crates/logbook-core/src/slug.rs', lines 54:4-72:5
    Visibility: public -/
@[rust_loop]
def slug.make_slug_loop
  (title : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (gap : Bool)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, gap1, i1) => slug.make_slug_loop.body title out1 gap1 i1)
    (out, gap, i)

/-- [logbook_core::slug::make_slug]:
    Source: 'crates/logbook-core/src/slug.rs', lines 50:0-74:1
    Visibility: public -/
def slug.make_slug
  (title : Slice Std.U8) (id : Std.U64) : Result (alloc.vec.Vec Std.U8) := do
  let out ←
    slug.make_slug_loop title (alloc.vec.Vec.new Std.U8) false 0#usize
  let i := alloc.vec.Vec.len out
  if i = 0#usize
  then slug.fallback id
  else ok out

/-- [logbook_core::video::YOUTUBE_ID_LEN]
    Source: 'crates/logbook-core/src/video.rs', lines 8:0-8:37
    Visibility: public -/
@[global_simps, irreducible] def video.YOUTUBE_ID_LEN : Std.Usize := 11#usize

/-- [logbook_core::video::is_id_byte]:
    Source: 'crates/logbook-core/src/video.rs', lines 11:0-17:1 -/
def video.is_id_byte (c : Std.U8) : Result Bool := do
  if c >= 65#u8
  then
    if c <= 90#u8
    then ok true
    else
      if c >= 97#u8
      then
        if c <= 122#u8
        then ok true
        else
          if c >= 48#u8
          then
            if c <= 57#u8
            then ok true
            else if c = 95#u8
                 then ok true
                 else ok (c = 45#u8)
          else if c = 95#u8
               then ok true
               else ok (c = 45#u8)
      else
        if c >= 48#u8
        then
          if c <= 57#u8
          then ok true
          else if c = 95#u8
               then ok true
               else ok (c = 45#u8)
        else if c = 95#u8
             then ok true
             else ok (c = 45#u8)
  else
    if c >= 97#u8
    then
      if c <= 122#u8
      then ok true
      else
        if c >= 48#u8
        then
          if c <= 57#u8
          then ok true
          else if c = 95#u8
               then ok true
               else ok (c = 45#u8)
        else if c = 95#u8
             then ok true
             else ok (c = 45#u8)
    else
      if c >= 48#u8
      then
        if c <= 57#u8
        then ok true
        else if c = 95#u8
             then ok true
             else ok (c = 45#u8)
      else if c = 95#u8
           then ok true
           else ok (c = 45#u8)

/-- [logbook_core::video::starts]: loop body 0:
    Source: 'crates/logbook-core/src/video.rs', lines 25:4-32:1 -/
@[rust_loop_body]
def video.starts_loop.body
  (s : Slice Std.U8) (p : Slice Std.U8) (j : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i := Slice.len p
  if j < i
  then
    let i1 ← Slice.index_usize s j
    let i2 ← Slice.index_usize p j
    if i1 != i2
    then ok (done false)
    else let j1 ← j + 1#usize
         ok (cont j1)
  else ok (done true)

/-- [logbook_core::video::starts]: loop 0:
    Source: 'crates/logbook-core/src/video.rs', lines 25:4-32:1 -/
@[rust_loop]
def video.starts_loop
  (s : Slice Std.U8) (p : Slice Std.U8) (j : Std.Usize) : Result Bool := do
  loop
    (fun j1 => video.starts_loop.body s p j1)
    j

/-- [logbook_core::video::starts]:
    Source: 'crates/logbook-core/src/video.rs', lines 20:0-32:1 -/
def video.starts (s : Slice Std.U8) (p : Slice Std.U8) : Result Bool := do
  let i := Slice.len s
  let i1 := Slice.len p
  if i < i1
  then ok false
  else video.starts_loop s p 0#usize

/-- [logbook_core::video::youtube_prefix]:
    Source: 'crates/logbook-core/src/video.rs', lines 36:0-52:1 -/
def video.youtube_prefix (url : Slice Std.U8) : Result Std.Usize := do
  let s ←
    lift (Array.to_slice
      (Array.make 32#usize [
        104#u8, 116#u8, 116#u8, 112#u8, 115#u8, 58#u8, 47#u8, 47#u8, 119#u8,
        119#u8, 119#u8, 46#u8, 121#u8, 111#u8, 117#u8, 116#u8, 117#u8, 98#u8,
        101#u8, 46#u8, 99#u8, 111#u8, 109#u8, 47#u8, 119#u8, 97#u8, 116#u8,
        99#u8, 104#u8, 63#u8, 118#u8, 61#u8
        ]))
  let b ← video.starts url s
  if b
  then ok 32#usize
  else
    let s1 ←
      lift (Array.to_slice
        (Array.make 28#usize [
          104#u8, 116#u8, 116#u8, 112#u8, 115#u8, 58#u8, 47#u8, 47#u8, 121#u8,
          111#u8, 117#u8, 116#u8, 117#u8, 98#u8, 101#u8, 46#u8, 99#u8, 111#u8,
          109#u8, 47#u8, 119#u8, 97#u8, 116#u8, 99#u8, 104#u8, 63#u8, 118#u8,
          61#u8
          ]))
    let b1 ← video.starts url s1
    if b1
    then ok 28#usize
    else
      let s2 ←
        lift (Array.to_slice
          (Array.make 30#usize [
            104#u8, 116#u8, 116#u8, 112#u8, 115#u8, 58#u8, 47#u8, 47#u8,
            109#u8, 46#u8, 121#u8, 111#u8, 117#u8, 116#u8, 117#u8, 98#u8,
            101#u8, 46#u8, 99#u8, 111#u8, 109#u8, 47#u8, 119#u8, 97#u8, 116#u8,
            99#u8, 104#u8, 63#u8, 118#u8, 61#u8
            ]))
      let b2 ← video.starts url s2
      if b2
      then ok 30#usize
      else
        let s3 ←
          lift (Array.to_slice
            (Array.make 17#usize [
              104#u8, 116#u8, 116#u8, 112#u8, 115#u8, 58#u8, 47#u8, 47#u8,
              121#u8, 111#u8, 117#u8, 116#u8, 117#u8, 46#u8, 98#u8, 101#u8,
              47#u8
              ]))
        let b3 ← video.starts url s3
        if b3
        then ok 17#usize
        else
          let s4 ←
            lift (Array.to_slice
              (Array.make 31#usize [
                104#u8, 116#u8, 116#u8, 112#u8, 115#u8, 58#u8, 47#u8, 47#u8,
                119#u8, 119#u8, 119#u8, 46#u8, 121#u8, 111#u8, 117#u8, 116#u8,
                117#u8, 98#u8, 101#u8, 46#u8, 99#u8, 111#u8, 109#u8, 47#u8,
                115#u8, 104#u8, 111#u8, 114#u8, 116#u8, 115#u8, 47#u8
                ]))
          let b4 ← video.starts url s4
          if b4
          then ok 31#usize
          else
            let s5 ←
              lift (Array.to_slice
                (Array.make 27#usize [
                  104#u8, 116#u8, 116#u8, 112#u8, 115#u8, 58#u8, 47#u8, 47#u8,
                  121#u8, 111#u8, 117#u8, 116#u8, 117#u8, 98#u8, 101#u8, 46#u8,
                  99#u8, 111#u8, 109#u8, 47#u8, 115#u8, 104#u8, 111#u8, 114#u8,
                  116#u8, 115#u8, 47#u8
                  ]))
            let b5 ← video.starts url s5
            if b5
            then ok 27#usize
            else ok 0#usize

/-- [logbook_core::video::id_at]: loop body 0:
    Source: 'crates/logbook-core/src/video.rs', lines 61:4-69:1 -/
@[rust_loop_body]
def video.id_at_loop.body
  (url : Slice Std.U8) («at» : Std.Usize) (j : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if j < video.YOUTUBE_ID_LEN
  then
    let i ← «at» + j
    let i1 ← Slice.index_usize url i
    let b ← video.is_id_byte i1
    if b
    then let j1 ← j + 1#usize
         ok (cont j1)
    else ok (done false)
  else
    let «end» ← «at» + video.YOUTUBE_ID_LEN
    let i := Slice.len url
    if «end» = i
    then ok (done true)
    else
      let i1 ← Slice.index_usize url «end»
      if i1 = 63#u8
      then ok (done true)
      else if i1 = 38#u8
           then ok (done true)
           else ok (done (i1 = 35#u8))

/-- [logbook_core::video::id_at]: loop 0:
    Source: 'crates/logbook-core/src/video.rs', lines 61:4-69:1 -/
@[rust_loop]
def video.id_at_loop
  (url : Slice Std.U8) («at» : Std.Usize) (j : Std.Usize) : Result Bool := do
  loop
    (fun j1 => video.id_at_loop.body url «at» j1)
    j

/-- [logbook_core::video::id_at]:
    Source: 'crates/logbook-core/src/video.rs', lines 56:0-69:1 -/
def video.id_at (url : Slice Std.U8) («at» : Std.Usize) : Result Bool := do
  let i := Slice.len url
  if «at» > i
  then ok false
  else
    let i1 := Slice.len url
    let i2 ← i1 - «at»
    if i2 < video.YOUTUBE_ID_LEN
    then ok false
    else video.id_at_loop url «at» 0#usize

/-- [logbook_core::video::youtube_id]:
    Source: 'crates/logbook-core/src/video.rs', lines 79:0-86:1
    Visibility: public -/
def video.youtube_id (url : Slice Std.U8) : Result (Option Std.Usize) := do
  let «at» ← video.youtube_prefix url
  if «at» > 0#usize
  then let b ← video.id_at url «at»
       if b
       then ok (some «at»)
       else ok none
  else ok none

end logbook_core
