-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [logbook_core]: function definitions
module
public import Aeneas
public import LogbookCore.Types
public import LogbookCore.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace logbook_core

/-- Trait implementation: [core::option::{impl core::fmt::Debug for core::option::Option<T>}]
    Source: '/rustc/library/core/src/option.rs', lines 592:15-592:20
    Name pattern: [core::fmt::Debug<core::option::Option<@T>>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<core::option::Option<@T>>"]
def core.option.Option.Insts.CoreFmtDebug {T : Type} (fmtDebugInst :
  core.fmt.Debug T) : core.fmt.Debug (Option T) := {
  fmt := core.option.Option.Insts.CoreFmtDebug.fmt fmtDebugInst
}

/-- [logbook_core::media::is_lower_hex]:
    Source: 'crates/logbook-core/src/media.rs', lines 7:0-9:1 -/
def media.is_lower_hex (c : Std.U8) : Result Bool := do
  if c >= 48#u8
  then
    if c <= 57#u8
    then ok true
    else if c >= 97#u8
         then ok (c <= 102#u8)
         else ok false
  else if c >= 97#u8
       then ok (c <= 102#u8)
       else ok false

/-- [logbook_core::media::tail_is]: loop body 0:
    Source: 'crates/logbook-core/src/media.rs', lines 17:4-24:1 -/
@[rust_loop_body]
def media.tail_is_loop.body
  (key : Slice Std.U8) («at» : Std.Usize) (ext : Slice Std.U8)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len ext
  if i < i1
  then
    let i2 ← «at» + i
    let i3 ← Slice.index_usize key i2
    let i4 ← Slice.index_usize ext i
    if i3 != i4
    then ok (done false)
    else let i5 ← i + 1#usize
         ok (cont i5)
  else ok (done true)

/-- [logbook_core::media::tail_is]: loop 0:
    Source: 'crates/logbook-core/src/media.rs', lines 17:4-24:1 -/
@[rust_loop]
def media.tail_is_loop
  (key : Slice Std.U8) («at» : Std.Usize) (ext : Slice Std.U8)
  (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => media.tail_is_loop.body key «at» ext i1)
    i

/-- [logbook_core::media::tail_is]:
    Source: 'crates/logbook-core/src/media.rs', lines 12:0-24:1 -/
def media.tail_is
  (key : Slice Std.U8) («at» : Std.Usize) (ext : Slice Std.U8) :
  Result Bool
  := do
  let i := Slice.len key
  let i1 := Slice.len ext
  let i2 ← «at» + i1
  if i != i2
  then ok false
  else media.tail_is_loop key «at» ext 0#usize

/-- [logbook_core::media::media_key_ok]: loop body 0:
    Source: 'crates/logbook-core/src/media.rs', lines 34:4-45:1
    Visibility: public -/
@[rust_loop_body]
def media.media_key_ok_loop.body
  (key : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if i < 64#usize
  then
    let i1 ← Slice.index_usize key i
    let b ← media.is_lower_hex i1
    if b
    then let i2 ← i + 1#usize
         ok (cont i2)
    else ok (done false)
  else
    let i1 ← Slice.index_usize key 64#usize
    if i1 = 46#u8
    then
      let s ←
        lift (Array.to_slice (Array.make 3#usize [ 112#u8, 110#u8, 103#u8 ]))
      let b ← media.tail_is key 65#usize s
      if b
      then ok (done true)
      else
        let s1 ←
          lift (Array.to_slice (Array.make 3#usize [ 106#u8, 112#u8, 103#u8 ]))
        let b1 ← media.tail_is key 65#usize s1
        if b1
        then ok (done true)
        else
          let s2 ←
            lift (Array.to_slice
              (Array.make 3#usize [ 103#u8, 105#u8, 102#u8 ]))
          let b2 ← media.tail_is key 65#usize s2
          if b2
          then ok (done true)
          else
            let s3 ←
              lift (Array.to_slice
                (Array.make 4#usize [ 119#u8, 101#u8, 98#u8, 112#u8 ]))
            let b3 ← media.tail_is key 65#usize s3
            ok (done b3)
    else ok (done false)

/-- [logbook_core::media::media_key_ok]: loop 0:
    Source: 'crates/logbook-core/src/media.rs', lines 34:4-45:1
    Visibility: public -/
@[rust_loop]
def media.media_key_ok_loop
  (key : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => media.media_key_ok_loop.body key i1)
    i

/-- [logbook_core::media::media_key_ok]:
    Source: 'crates/logbook-core/src/media.rs', lines 29:0-45:1
    Visibility: public -/
def media.media_key_ok (key : Slice Std.U8) : Result Bool := do
  let i := Slice.len key
  if i < 68#usize
  then ok false
  else media.media_key_ok_loop key 0#usize

/-- [logbook_core::post::{impl core::fmt::Debug for logbook_core::post::Topic}::fmt]:
    Source: 'crates/logbook-core/src/post.rs', lines 18:9-18:14
    Visibility: public -/
def post.Topic.Insts.CoreFmtDebug.fmt
  (self : post.Topic) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | post.Topic.Ethereum => core.fmt.Formatter.write_str f (toStr "Ethereum")
  | post.Topic.Rust => core.fmt.Formatter.write_str f (toStr "Rust")
  | post.Topic.Surf => core.fmt.Formatter.write_str f (toStr "Surf")
  | post.Topic.Snowboarding =>
    core.fmt.Formatter.write_str f (toStr "Snowboarding")
  | post.Topic.JiuJitsu => core.fmt.Formatter.write_str f (toStr "JiuJitsu")
  | post.Topic.ClassicWow =>
    core.fmt.Formatter.write_str f (toStr "ClassicWow")

/-- Trait implementation: [logbook_core::post::{impl core::fmt::Debug for logbook_core::post::Topic}]
    Source: 'crates/logbook-core/src/post.rs', lines 18:9-18:14 -/
@[reducible]
def post.Topic.Insts.CoreFmtDebug : core.fmt.Debug post.Topic := {
  fmt := post.Topic.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::post::{impl core::fmt::Debug for logbook_core::post::State}::fmt]:
    Source: 'crates/logbook-core/src/post.rs', lines 7:9-7:14
    Visibility: public -/
def post.State.Insts.CoreFmtDebug.fmt
  (self : post.State) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | post.State.Draft => core.fmt.Formatter.write_str f (toStr "Draft")
  | post.State.Private => core.fmt.Formatter.write_str f (toStr "Private")
  | post.State.Public => core.fmt.Formatter.write_str f (toStr "Public")

/-- Trait implementation: [logbook_core::post::{impl core::fmt::Debug for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:9-7:14 -/
@[reducible]
def post.State.Insts.CoreFmtDebug : core.fmt.Debug post.State := {
  fmt := post.State.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::post::{impl core::fmt::Debug for logbook_core::post::Post}::fmt]:
    Source: 'crates/logbook-core/src/post.rs', lines 32:9-32:14
    Visibility: public -/
def post.Post.Insts.CoreFmtDebug.fmt
  (self : post.Post) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.id
  let dyn1 := Dyn.mk _ post.State.Insts.CoreFmtDebug self.state
  let dyn2 := Dyn.mk _ post.Topic.Insts.CoreFmtDebug self.topic
  let dyn3 := Dyn.mk _ core.fmt.DebugU32 self.word_count
  let dyn4 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.slug
  let dyn5 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.title
  let dyn6 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.summary
  let dyn7 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.tags
  let dyn8 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.body_html
  let dyn9 :=
    Dyn.mk _ (core.option.Option.Insts.CoreFmtDebug (core.fmt.DebugVec
      core.fmt.DebugU8)) self.published_at
  let dyn10 :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec core.fmt.DebugU8))
      self.updated_at
  let values :=
    Array.to_slice
      (Array.make 11#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 11#usize [
        toStr "id", toStr "state", toStr "topic", toStr "word_count", toStr
        "slug", toStr "title", toStr "summary", toStr "tags", toStr
        "body_html", toStr "published_at", toStr "updated_at"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "Post") s values

/-- Trait implementation: [logbook_core::post::{impl core::fmt::Debug for logbook_core::post::Post}]
    Source: 'crates/logbook-core/src/post.rs', lines 32:9-32:14 -/
@[reducible]
def post.Post.Insts.CoreFmtDebug : core.fmt.Debug post.Post := {
  fmt := post.Post.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::policy::{impl core::fmt::Debug for logbook_core::policy::PublicPost}::fmt]:
    Source: 'crates/logbook-core/src/policy.rs', lines 12:9-12:14
    Visibility: public -/
def policy.PublicPost.Insts.CoreFmtDebug.fmt
  (self : policy.PublicPost) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared post.Post.Insts.CoreFmtDebug) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "PublicPost") dyn

/-- Trait implementation: [logbook_core::policy::{impl core::fmt::Debug for logbook_core::policy::PublicPost}]
    Source: 'crates/logbook-core/src/policy.rs', lines 12:9-12:14 -/
@[reducible]
def policy.PublicPost.Insts.CoreFmtDebug : core.fmt.Debug policy.PublicPost
  := {
  fmt := policy.PublicPost.Insts.CoreFmtDebug.fmt
}

/-- [logbook_core::post::clone_opt]:
    Source: 'crates/logbook-core/src/post.rs', lines 50:0-55:1 -/
def post.clone_opt
  (v : Option (alloc.vec.Vec Std.U8)) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  match v with
  | none => ok none
  | some b =>
    let v1 ← alloc.vec.CloneVec.clone core.clone.CloneU8 b
    ok (some v1)

/-- [logbook_core::post::{impl core::clone::Clone for logbook_core::post::Post}::clone]:
    Source: 'crates/logbook-core/src/post.rs', lines 58:4-72:5
    Visibility: public -/
def post.Post.Insts.CoreCloneClone.clone
  (self : post.Post) : Result post.Post := do
  let v ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.slug
  let v1 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.title
  let v2 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.summary
  let v3 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.tags
  let v4 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.body_html
  let o ← post.clone_opt self.published_at
  let v5 ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.updated_at
  ok
    {
      self
        with
        slug := v,
        title := v1,
        summary := v2,
        tags := v3,
        body_html := v4,
        published_at := o,
        updated_at := v5
    }

/-- [logbook_core::policy::{impl core::clone::Clone for logbook_core::policy::PublicPost}::clone]:
    Source: 'crates/logbook-core/src/policy.rs', lines 12:16-12:21
    Visibility: public -/
def policy.PublicPost.Insts.CoreCloneClone.clone
  (self : policy.PublicPost) : Result policy.PublicPost := do
  let p ← post.Post.Insts.CoreCloneClone.clone self
  ok p

/-- Trait implementation: [logbook_core::policy::{impl core::clone::Clone for logbook_core::policy::PublicPost}]
    Source: 'crates/logbook-core/src/policy.rs', lines 12:16-12:21 -/
@[reducible]
def policy.PublicPost.Insts.CoreCloneClone : core.clone.Clone policy.PublicPost
  := {
  clone := policy.PublicPost.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [logbook_core::policy::{impl core::marker::StructuralPartialEq for logbook_core::policy::PublicPost}]
    Source: 'crates/logbook-core/src/policy.rs', lines 12:23-12:32 -/
@[reducible]
def policy.PublicPost.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq policy.PublicPost := {
}

/-- [logbook_core::post::{impl core::cmp::PartialEq<logbook_core::post::Topic> for logbook_core::post::Topic}::eq]:
    Source: 'crates/logbook-core/src/post.rs', lines 18:29-18:38
    Visibility: public -/
def post.Topic.Insts.CoreCmpPartialEqTopic.eq
  (self : post.Topic) (other : post.Topic) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [logbook_core::post::{impl core::cmp::PartialEq<logbook_core::post::State> for logbook_core::post::State}::eq]:
    Source: 'crates/logbook-core/src/post.rs', lines 7:29-7:38
    Visibility: public -/
def post.State.Insts.CoreCmpPartialEqState.eq
  (self : post.State) (other : post.State) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [logbook_core::post::{impl core::cmp::PartialEq<logbook_core::post::Post> for logbook_core::post::Post}::eq]:
    Source: 'crates/logbook-core/src/post.rs', lines 32:16-32:25
    Visibility: public -/
def post.Post.Insts.CoreCmpPartialEqPost.eq
  (self : post.Post) (other : post.Post) : Result Bool := do
  if self.id = other.id
  then
    if self.word_count = other.word_count
    then
      let b ←
        post.State.Insts.CoreCmpPartialEqState.eq self.state other.state
      if b
      then
        let b1 ←
          post.Topic.Insts.CoreCmpPartialEqTopic.eq self.topic other.topic
        if b1
        then
          let b2 ←
            alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8 
              self.slug other.slug
          if b2
          then
            let b3 ←
              alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8
                self.title other.title
            if b3
            then
              let b4 ←
                alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8
                  self.summary other.summary
              if b4
              then
                let b5 ←
                  alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8
                    self.tags other.tags
                if b5
                then
                  let b6 ←
                    alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8
                      self.body_html other.body_html
                  if b6
                  then
                    let b7 ←
                      core.option.Option.Insts.CoreCmpPartialEqOption.eq
                        (core.cmp.PartialEqVec core.cmp.PartialEqU8)
                        self.published_at other.published_at
                    if b7
                    then
                      alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8
                        self.updated_at other.updated_at
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- [logbook_core::policy::{impl core::cmp::PartialEq<logbook_core::policy::PublicPost> for logbook_core::policy::PublicPost}::eq]:
    Source: 'crates/logbook-core/src/policy.rs', lines 12:23-12:32
    Visibility: public -/
def policy.PublicPost.Insts.CoreCmpPartialEqPublicPost.eq
  (self : policy.PublicPost) (other : policy.PublicPost) : Result Bool := do
  post.Post.Insts.CoreCmpPartialEqPost.eq self other

/-- Trait implementation: [logbook_core::policy::{impl core::cmp::PartialEq<logbook_core::policy::PublicPost> for logbook_core::policy::PublicPost}]
    Source: 'crates/logbook-core/src/policy.rs', lines 12:23-12:32 -/
@[reducible]
def policy.PublicPost.Insts.CoreCmpPartialEqPublicPost : core.cmp.PartialEq
  policy.PublicPost policy.PublicPost := {
  eq := policy.PublicPost.Insts.CoreCmpPartialEqPublicPost.eq
}

/-- [logbook_core::policy::{impl core::cmp::Eq for logbook_core::policy::PublicPost}::assert_fields_are_eq]:
    Source: 'crates/logbook-core/src/policy.rs', lines 12:34-12:36
    Visibility: public -/
def policy.PublicPost.Insts.CoreCmpEq.assert_fields_are_eq
  (self : policy.PublicPost) : Result Unit := do
  ok ()

/-- Trait implementation: [logbook_core::policy::{impl core::cmp::Eq for logbook_core::policy::PublicPost}]
    Source: 'crates/logbook-core/src/policy.rs', lines 12:34-12:36 -/
@[reducible]
def policy.PublicPost.Insts.CoreCmpEq : core.cmp.Eq policy.PublicPost := {
  partialEqInst := policy.PublicPost.Insts.CoreCmpPartialEqPublicPost
  assert_fields_are_eq :=
    policy.PublicPost.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [logbook_core::policy::{logbook_core::policy::PublicPost}::post]:
    Source: 'crates/logbook-core/src/policy.rs', lines 18:4-20:5
    Visibility: public -/
def policy.PublicPost.post (self : policy.PublicPost) : Result post.Post := do
  ok self

/-- [logbook_core::policy::reveal]:
    Source: 'crates/logbook-core/src/policy.rs', lines 26:0-31:1
    Visibility: public -/
def policy.reveal (p : post.Post) : Result (Option policy.PublicPost) := do
  match p.state with
  | post.State.Draft => ok none
  | post.State.Private => ok none
  | post.State.Public => ok (some p)

/-- [logbook_core::policy::filter_public]: loop body 0:
    Source: 'crates/logbook-core/src/policy.rs', lines 38:4-43:5
    Visibility: public -/
@[rust_loop_body]
def policy.filter_public_loop.body
  (ps : Slice post.Post) (out : alloc.vec.Vec policy.PublicPost)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec policy.PublicPost) × Std.Usize)
    (alloc.vec.Vec policy.PublicPost))
  := do
  let i1 := Slice.len ps
  if i < i1
  then
    let p ← Slice.index_usize ps i
    let p1 ← post.Post.Insts.CoreCloneClone.clone p
    let o ← policy.reveal p1
    let out1 ←
      match o with
      | none => ok out
      | some q => alloc.vec.Vec.push out q
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [logbook_core::policy::filter_public]: loop 0:
    Source: 'crates/logbook-core/src/policy.rs', lines 38:4-43:5
    Visibility: public -/
@[rust_loop]
def policy.filter_public_loop
  (ps : Slice post.Post) (out : alloc.vec.Vec policy.PublicPost)
  (i : Std.Usize) :
  Result (alloc.vec.Vec policy.PublicPost)
  := do
  loop
    (fun (out1, i1) => policy.filter_public_loop.body ps out1 i1)
    (out, i)

/-- [logbook_core::policy::filter_public]:
    Source: 'crates/logbook-core/src/policy.rs', lines 35:0-45:1
    Visibility: public -/
@[reducible]
def policy.filter_public
  (ps : Slice post.Post) : Result (alloc.vec.Vec policy.PublicPost) := do
  policy.filter_public_loop ps (alloc.vec.Vec.new policy.PublicPost) 0#usize

/-- [logbook_core::post::WORDS_PER_MINUTE]
    Source: 'crates/logbook-core/src/post.rs', lines 4:0-4:38
    Visibility: public -/
@[global_simps, irreducible] def post.WORDS_PER_MINUTE : Std.U32 := 220#u32

/-- [logbook_core::post::{impl core::clone::Clone for logbook_core::post::State}::clone]:
    Source: 'crates/logbook-core/src/post.rs', lines 7:16-7:21
    Visibility: public -/
def post.State.Insts.CoreCloneClone.clone
  (self : post.State) : Result post.State := do
  ok self

/-- Trait implementation: [logbook_core::post::{impl core::clone::Clone for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:16-7:21 -/
@[reducible]
def post.State.Insts.CoreCloneClone : core.clone.Clone post.State := {
  clone := post.State.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [logbook_core::post::{impl core::marker::Copy for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:23-7:27 -/
@[reducible]
def post.State.Insts.CoreMarkerCopy : core.marker.Copy post.State := {
  cloneInst := post.State.Insts.CoreCloneClone
}

/-- Trait implementation: [logbook_core::post::{impl core::marker::StructuralPartialEq for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:29-7:38 -/
@[reducible]
def post.State.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq post.State := {
}

/-- Trait implementation: [logbook_core::post::{impl core::cmp::PartialEq<logbook_core::post::State> for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:29-7:38 -/
@[reducible]
def post.State.Insts.CoreCmpPartialEqState : core.cmp.PartialEq post.State
  post.State := {
  eq := post.State.Insts.CoreCmpPartialEqState.eq
}

/-- Trait implementation: [logbook_core::post::{impl core::cmp::Eq for logbook_core::post::State}]
    Source: 'crates/logbook-core/src/post.rs', lines 7:40-7:42 -/
@[reducible]
impl_def post.State.Insts.CoreCmpEq : core.cmp.Eq post.State := {
  partialEqInst := post.State.Insts.CoreCmpPartialEqState
  assert_fields_are_eq := core.cmp.Eq.assert_fields_are_eq.default
    post.State.Insts.CoreCmpEq
}

/-- [logbook_core::post::{impl core::clone::Clone for logbook_core::post::Topic}::clone]:
    Source: 'crates/logbook-core/src/post.rs', lines 18:16-18:21
    Visibility: public -/
def post.Topic.Insts.CoreCloneClone.clone
  (self : post.Topic) : Result post.Topic := do
  ok self

/-- Trait implementation: [logbook_core::post::{impl core::clone::Clone for logbook_core::post::Topic}]
    Source: 'crates/logbook-core/src/post.rs', lines 18:16-18:21 -/
@[reducible]
def post.Topic.Insts.CoreCloneClone : core.clone.Clone post.Topic := {
  clone := post.Topic.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [logbook_core::post::{impl core::marker::Copy for logbook_core::post::Topic}]
    Source: 'crates/logbook-core/src/post.rs', lines 18:23-18:27 -/
@[reducible]
def post.Topic.Insts.CoreMarkerCopy : core.marker.Copy post.Topic := {
  cloneInst := post.Topic.Insts.CoreCloneClone
}

/-- Trait implementation: [logbook_core::post::{impl core::marker::StructuralPartialEq for logbook_core::post::Topic}]
    Source: 'crates/logbook-core/src/post.rs', lines 18:29-18:38 -/
@[reducible]
def post.Topic.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq post.Topic := {
}

/-- Trait implementation: [logbook_core::post::{impl core::cmp::PartialEq<logbook_core::post::Topic> for logbook_core::post::Topic}]
    Source: 'crates/logbook-core/src/post.rs', lines 18:29-18:38 -/
@[reducible]
def post.Topic.Insts.CoreCmpPartialEqTopic : core.cmp.PartialEq post.Topic
  post.Topic := {
  eq := post.Topic.Insts.CoreCmpPartialEqTopic.eq
}

/-- Trait implementation: [logbook_core::post::{impl core::cmp::Eq for logbook_core::post::Topic}]
    Source: 'crates/logbook-core/src/post.rs', lines 18:40-18:42 -/
@[reducible]
impl_def post.Topic.Insts.CoreCmpEq : core.cmp.Eq post.Topic := {
  partialEqInst := post.Topic.Insts.CoreCmpPartialEqTopic
  assert_fields_are_eq := core.cmp.Eq.assert_fields_are_eq.default
    post.Topic.Insts.CoreCmpEq
}

/-- Trait implementation: [logbook_core::post::{impl core::marker::StructuralPartialEq for logbook_core::post::Post}]
    Source: 'crates/logbook-core/src/post.rs', lines 32:16-32:25 -/
@[reducible]
def post.Post.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq post.Post := {
}

/-- Trait implementation: [logbook_core::post::{impl core::cmp::PartialEq<logbook_core::post::Post> for logbook_core::post::Post}]
    Source: 'crates/logbook-core/src/post.rs', lines 32:16-32:25 -/
@[reducible]
def post.Post.Insts.CoreCmpPartialEqPost : core.cmp.PartialEq post.Post
  post.Post := {
  eq := post.Post.Insts.CoreCmpPartialEqPost.eq
}

/-- [logbook_core::post::{impl core::cmp::Eq for logbook_core::post::Post}::assert_fields_are_eq]:
    Source: 'crates/logbook-core/src/post.rs', lines 32:27-32:29
    Visibility: public -/
def post.Post.Insts.CoreCmpEq.assert_fields_are_eq
  (self : post.Post) : Result Unit := do
  ok ()

/-- Trait implementation: [logbook_core::post::{impl core::cmp::Eq for logbook_core::post::Post}]
    Source: 'crates/logbook-core/src/post.rs', lines 32:27-32:29 -/
@[reducible]
def post.Post.Insts.CoreCmpEq : core.cmp.Eq post.Post := {
  partialEqInst := post.Post.Insts.CoreCmpPartialEqPost
  assert_fields_are_eq := post.Post.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- Trait implementation: [logbook_core::post::{impl core::clone::Clone for logbook_core::post::Post}]
    Source: 'crates/logbook-core/src/post.rs', lines 57:0-73:1 -/
@[reducible]
def post.Post.Insts.CoreCloneClone : core.clone.Clone post.Post := {
  clone := post.Post.Insts.CoreCloneClone.clone
}

/-- [logbook_core::post::reading_minutes]:
    Source: 'crates/logbook-core/src/post.rs', lines 78:0-83:1
    Visibility: public -/
def post.reading_minutes (words : Std.U32) : Result Std.U32 := do
  let full ← words / post.WORDS_PER_MINUTE
  let rest ← words % post.WORDS_PER_MINUTE
  let minutes ← if rest = 0#u32
                  then ok full
                  else full + 1#u32
  if minutes = 0#u32
  then ok 1#u32
  else ok minutes

/-- [logbook_core::slug::SLUG_MAX]
    Source: 'crates/logbook-core/src/slug.rs', lines 7:0-7:31
    Visibility: public -/
@[global_simps, irreducible] def slug.SLUG_MAX : Std.Usize := 80#usize

/-- [logbook_core::slug::lower]:
    Source: 'crates/logbook-core/src/slug.rs', lines 11:0-13:1 -/
def slug.lower (c : Std.U8) : Result Std.U8 := do
  if c >= 65#u8
  then if c <= 90#u8
       then c + 32#u8
       else ok c
  else ok c

/-- [logbook_core::slug::is_slug_char]:
    Source: 'crates/logbook-core/src/slug.rs', lines 15:0-17:1 -/
def slug.is_slug_char (c : Std.U8) : Result Bool := do
  if c >= 97#u8
  then
    if c <= 122#u8
    then ok true
    else if c >= 48#u8
         then ok (c <= 57#u8)
         else ok false
  else if c >= 48#u8
       then ok (c <= 57#u8)
       else ok false

/-- [logbook_core::slug::fallback]: loop body 0:
    Source: 'crates/logbook-core/src/slug.rs', lines 23:4-31:5 -/
@[rust_loop_body]
def slug.fallback_loop0.body
  (digits : alloc.vec.Vec Std.U8) (n : Std.U64) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.U64) (alloc.vec.Vec
    Std.U8))
  := do
  let i ← n % 10#u64
  let i1 ← lift (UScalar.cast .U8 i)
  let i2 ← 48#u8 + i1
  let digits1 ← alloc.vec.Vec.push digits i2
  let n1 ← n / 10#u64
  if n1 = 0#u64
  then ok (done digits1)
  else ok (cont (digits1, n1))

/-- [logbook_core::slug::fallback]: loop 0:
    Source: 'crates/logbook-core/src/slug.rs', lines 23:4-31:5 -/
@[rust_loop]
def slug.fallback_loop0
  (digits : alloc.vec.Vec Std.U8) (n : Std.U64) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (digits1, n1) => slug.fallback_loop0.body digits1 n1)
    (digits, n)

/-- [logbook_core::slug::fallback]: loop body 1:
    Source: 'crates/logbook-core/src/slug.rs', lines 34:4-37:5 -/
@[rust_loop_body]
def slug.fallback_loop1.body
  (digits : alloc.vec.Vec Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i > 0#usize
  then
    let i1 ← i - 1#usize
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8) digits
        i1
    let out1 ← alloc.vec.Vec.push out i2
    ok (cont (out1, i1))
  else ok (done out)

/-- [logbook_core::slug::fallback]: loop 1:
    Source: 'crates/logbook-core/src/slug.rs', lines 34:4-37:5 -/
@[rust_loop]
def slug.fallback_loop1
  (digits : alloc.vec.Vec Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => slug.fallback_loop1.body digits out1 i1)
    (out, i)

/-- [logbook_core::slug::fallback]:
    Source: 'crates/logbook-core/src/slug.rs', lines 20:0-39:1 -/
def slug.fallback (id : Std.U64) : Result (alloc.vec.Vec Std.U8) := do
  let digits ← slug.fallback_loop0 (alloc.vec.Vec.new Std.U8) id
  let s ←
    lift (Array.to_slice
      (Array.make 5#usize [ 112#u8, 111#u8, 115#u8, 116#u8, 45#u8 ]))
  let out ← alloc.slice.Slice.to_vec core.clone.CloneU8 s
  let i := alloc.vec.Vec.len digits
  slug.fallback_loop1 digits out i

/-- [logbook_core::slug::make_slug]: loop body 0:
    Source: 'crates/logbook-core/src/slug.rs', lines 54:4-72:5
    Visibility: public -/
@[rust_loop_body]
def slug.make_slug_loop.body
  (title : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (gap : Bool)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Bool × Std.Usize)
    (alloc.vec.Vec Std.U8))
  := do
  let i1 := Slice.len title
  if i < i1
  then
    let i2 ← Slice.index_usize title i
    let c ← slug.lower i2
    let b ← slug.is_slug_char c
    if b
    then
      if gap
      then
        let i3 := alloc.vec.Vec.len out
        if i3 > 0#usize
        then
          let i4 := alloc.vec.Vec.len out
          let i5 ← i4 + 2#usize
          if i5 > slug.SLUG_MAX
          then ok (done out)
          else
            let out1 ← alloc.vec.Vec.push out 45#u8
            let i6 := alloc.vec.Vec.len out1
            let i7 ← i6 + 1#usize
            if i7 > slug.SLUG_MAX
            then ok (done out1)
            else
              let out2 ← alloc.vec.Vec.push out1 c
              let i8 ← i + 1#usize
              ok (cont (out2, false, i8))
        else
          let i4 := alloc.vec.Vec.len out
          let i5 ← i4 + 1#usize
          if i5 > slug.SLUG_MAX
          then ok (done out)
          else
            let out1 ← alloc.vec.Vec.push out c
            let i6 ← i + 1#usize
            ok (cont (out1, false, i6))
      else
        let i3 := alloc.vec.Vec.len out
        let i4 ← i3 + 1#usize
        if i4 > slug.SLUG_MAX
        then ok (done out)
        else
          let out1 ← alloc.vec.Vec.push out c
          let i5 ← i + 1#usize
          ok (cont (out1, false, i5))
    else
      let gap1 ← if c != 39#u8
                   then ok true
                   else ok gap
      let i3 ← i + 1#usize
      ok (cont (out, gap1, i3))
  else ok (done out)

/-- [logbook_core::slug::make_slug]: loop 0:
    Source: 'crates/logbook-core/src/slug.rs', lines 54:4-72:5
    Visibility: public -/
@[rust_loop]
def slug.make_slug_loop
  (title : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (gap : Bool)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, gap1, i1) => slug.make_slug_loop.body title out1 gap1 i1)
    (out, gap, i)

/-- [logbook_core::slug::make_slug]:
    Source: 'crates/logbook-core/src/slug.rs', lines 50:0-74:1
    Visibility: public -/
def slug.make_slug
  (title : Slice Std.U8) (id : Std.U64) : Result (alloc.vec.Vec Std.U8) := do
  let out ←
    slug.make_slug_loop title (alloc.vec.Vec.new Std.U8) false 0#usize
  let i := alloc.vec.Vec.len out
  if i = 0#usize
  then slug.fallback id
  else ok out

end logbook_core
