-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [logbook_core]: type definitions
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace logbook_core

/-- [logbook_core::post::State]
    Source: 'crates/logbook-core/src/post.rs', lines 8:0-15:1
    Visibility: public -/
@[discriminant isize]
inductive post.State where
| Draft : post.State
| Private : post.State
| Public : post.State

/-- [logbook_core::post::Post]
    Source: 'crates/logbook-core/src/post.rs', lines 22:0-38:1
    Visibility: public -/
structure post.Post where
  id : Std.U64
  state : post.State
  topic : alloc.vec.Vec Std.U8
  word_count : Std.U32
  slug : alloc.vec.Vec Std.U8
  title : alloc.vec.Vec Std.U8
  summary : alloc.vec.Vec Std.U8
  tags : alloc.vec.Vec Std.U8
  body_html : alloc.vec.Vec Std.U8
  published_at : Option (alloc.vec.Vec Std.U8)
  updated_at : alloc.vec.Vec Std.U8

/-- [logbook_core::policy::PublicPost]
    Source: 'crates/logbook-core/src/policy.rs', lines 13:0-13:28
    Visibility: public -/
@[reducible]
def policy.PublicPost := post.Post

end logbook_core
